Adding basic namespace and logo for PayRue
bonustrack/snapshot-spaces pull request #10
Opened 2020-09-10 18:48 UTC by AbstractBreazy

2020-09-11 02:32 UTC, e-asia commented on spaces/payrue/index.json
> +  "token": "0xa9E81167b02cC4a79E100e3e0AF8f6Cd97Cc2727",
There seem to be an issue with your the token, the interface doesn't seem compatible with it

2020-09-11 11:07 UTC, AbstractBreazy commented on spaces/payrue/index.json
> +  "token": "0xa9E81167b02cC4a79E100e3e0AF8f6Cd97Cc2727",
thats metamask wallet, I have not attached any tokens to it

2020-09-11 11:16 UTC, AbstractBreazy commented on spaces/payrue/index.json
> +  "token": "0xa9E81167b02cC4a79E100e3e0AF8f6Cd97Cc2727",
I entered the correct eth address in metamask, what could be the problem?

2020-09-11 11:29 UTC, e-asia commented on spaces/payrue/index.json
> +  "token": "0xa9E81167b02cC4a79E100e3e0AF8f6Cd97Cc2727",
Not sure what's wrong exactly with the token, i told my colleague to look into it he will get back to you.

2020-09-13 04:22 UTC, bonustrack commented on spaces/payrue/index.json
> +  "address": "0xa9E81167b02cC4a79E100e3e0AF8f6Cd97Cc2727",
The address doesn't seem to be a contract, it must be an ERC20 to work on the interface.

2020-09-14 08:49 UTC, AbstractBreazy commented on spaces/payrue/index.json
> +  "address": "0xa9E81167b02cC4a79E100e3e0AF8f6Cd97Cc2727",
if Binance Smart Chain contract/address would work since its compatible with MetaMask as well?

2020-09-15 05:55 UTC, bonustrack commented on spaces/payrue/index.json
> +  "address": "0xa9E81167b02cC4a79E100e3e0AF8f6Cd97Cc2727",
Yes it should. Does your token have a decimals function? If not you will need some custom setup, please join our Discord to get more info https://discord.snapshot.page

2020-09-22 02:49 UTC, e-asia requested changes

2020-09-22 02:49 UTC, e-asia commented on spaces/payrue/index.json
> +  "token": "0x9B44Df3318972bE845d83f961735609137C4C23c",
Something is wrong with the token, the call to query decimals() is failing. Is this a standard ERC20 token?

2020-09-22 10:43 UTC, AbstractBreazy commented on spaces/payrue/index.json
> +  "token": "0x9B44Df3318972bE845d83f961735609137C4C23c",
Sorry about that, I have fixed my mistake

2020-09-22 14:06 UTC, bonustrack commented on spaces/payrue/index.json
> +  "defaultView": "core",
```suggestion
  "defaultView": "all",
```

2020-09-22 14:06 UTC, merged