Add SFG space
bonustrack/snapshot-spaces pull request #108
Opened 2020-09-25 09:28 UTC by leonchan0810

**Add space for ...**  
  
Etherscan: https://etherscan.io/token/0x8a6ACA71A218301c7081d4e96D64292D3B275ce0
CoinGecko: https://www.coingecko.com/en/coins/s-finance
Website: https://s.finance
Twitter: https://twitter.com/SFinanceEx

2020-09-26 02:26 UTC, e-asia requested changes
![image](https://user-images.githubusercontent.com/8545464/94328160-560f0600-ffda-11ea-98c6-f6cd550f86c6.png)
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.

2020-09-28 08:28 UTC, leonchan0810 commented on spaces/domains.json
> +  "signal.s.finance": "s-finance"
@e-asia I fixed the style problem of the file skin.scss, please review it, thx.
@bonustrack please add this custom domain, thx

2020-09-28 16:15 UTC, leonchan0810 commented
@e-asia When can pr pass? Our team expect our snapshot page can be online before 1st Oct.
Is there anything I can do to speed up this process? Thanks.

2020-09-29 05:07 UTC, e-asia requested changes

2020-09-29 05:07 UTC, e-asia commented on spaces/s-finance/skin.scss
> +  --link-color: #EB3C00;
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
![image](https://user-images.githubusercontent.com/8545464/94514785-4a2a7a80-024c-11eb-9e0a-6888ac98295f.png)

2020-09-29 06:17 UTC, leonchan0810 commented on spaces/s-finance/skin.scss
> +  --link-color: #EB3C00;
Finally, I delete this file to use default skin.
@e-asia Please check it again. Thanks a lot.

2020-09-29 12:17 UTC, e-asia approved these changes

2020-09-29 12:32 UTC, merged