Add DANIMESQ-XDAI space
bonustrack/snapshot-spaces pull request #110
Opened 2020-09-25 19:24 UTC by DaniellMesquita

2020-09-26 03:04 UTC, e-asia requested changes

2020-09-26 03:04 UTC, e-asia commented on spaces/daniell-mesquita-xdai/index.json
> +}
Something is wrong with the token, the call to query decimals() is failing. Is this a standard ERC20 token?

2020-09-26 06:04 UTC, DaniellMesquita commented on spaces/daniell-mesquita-xdai/index.json
> +}
Probably I need to send it to XDAI to sync?

2020-09-27 02:32 UTC, e-asia commented on spaces/daniell-mesquita-xdai/index.json
> +}
@bonustrack Could you have a look on that token?

2020-09-30 01:34 UTC, bonustrack commented on spaces/daniell-mesquita-xdai/index.json
> +}
Looks good to me

2020-09-30 01:55 UTC, e-asia approved these changes

2020-09-30 02:23 UTC, merged