Add MEW space
bonustrack/snapshot-spaces pull request #111
Opened 2020-09-25 19:44 UTC by kirkins

Hello, we're creating an NFT Art based DAO type platform. Not sure if we are too early stage for snapshot but the voting feature would be useful for us.
  
Etherscan: https://etherscan.io/token/0xd17e374a7d49287f583ddfbdeb6ad4da21c00ce3
Website: https://kitten.network
Twitter: https://twitter.com/KittenNetwork

2020-09-26 03:05 UTC, e-asia requested changes

2020-09-26 03:05 UTC, e-asia commented on spaces/mew/skin.scss
> +.name {
The css selector should similar to the space key.
```suggestion
.mew {
```

2020-09-26 03:05 UTC, e-asia commented on spaces/mew/skin.scss
> +}
To use the default theme you will want to delete skin.scss from your space folder.

2020-09-26 22:47 UTC, kirkins commented on spaces/mew/skin.scss
> +}
Thank you, remove the file.

2020-09-27 02:48 UTC, e-asia approved these changes

2020-09-27 02:54 UTC, merged