Add PRIMA space
bonustrack/snapshot-spaces pull request #112
Opened 2020-09-26 01:28 UTC by rootdraws

**Add space for Prima**  
  
Etherscan: https://etherscan.io/token/0xc0B126a67AA9c2995472E75BC66C2F69f955fe16  
Twitter: https://twitter.com/rootdraws
Patreon: https://patreon.com/rootdraws
Kickstarter: https://www.kickstarter.com/profile/rootdraws/created
HIVE: https://peakd.com/@rootdraws

2020-09-26 03:07 UTC, e-asia requested changes

2020-09-26 03:07 UTC, e-asia commented on spaces/prima/skin.scss
> +.name {
The css selector should similar to the space key.
```suggestion
.prima {
```

2020-09-26 03:07 UTC, e-asia commented on spaces/prima/skin.scss
> +}
To use the default theme you will want to delete skin.scss from your space folder.

2020-09-26 21:07 UTC, rootdraws commented on spaces/prima/skin.scss
> +}
Hey, can you help me understand how to delete skinn.scss from my space folder?

2020-09-27 02:40 UTC, e-asia commented on spaces/prima/skin.scss
> +}
You delete skin.scss manually, `git status`, you should see skin css deleted `git add skin.scss`, `git commit -m "delete default skin"` and `git push`. It should work for me :)

2020-09-28 02:03 UTC, rootdraws commented
Thanks I'll reach out to you in a week or so, I'm waiting for colony to
update their project, because my ability to mint coins is tied up with
their service, and they've shut it down for a moment. I could do this
elsewhere, but I want to try and use some synergy.

Thank you for the response, talk to you in a bit.

On Sat, Sep 26, 2020 at 8:40 PM Jeremy <notifications@github.com> wrote:

> *@e-asia* commented on this pull request.
> ------------------------------
>
> In spaces/prima/skin.scss
> <https://github.com/bonustrack/snapshot-spaces/pull/112#discussion_r495518950>
> :
>
> > @@ -0,0 +1,10 @@
> +.name {
> +  --primary-color: #384aff;
> +  --bg-color: white;
> +  --text-color: #586069;
> +  --link-color: #111111;
> +  --heading-color: #111111;
> +  --border-color: #d1d5da;
> +  --header-bg: white;
> +  --block-bg: transparent;
> +}
>
> You delete skin.scss manually, git status, you should see skin css
> deleted git add skin.scss, git commit -m "delete default skin" and git
> push. It should work for me :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bonustrack/snapshot-spaces/pull/112#discussion_r495518950>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANABCRJW66XGWTPJNBPTBB3SH2Q3BANCNFSM4R2SLOCA>
> .
>

2020-10-06 12:19 UTC, e-asia commented
Closing this PR for now, feel free to open it again once you've done the changes.

2020-10-06 12:19 UTC, closed without merging