Add SDOGE space
bonustrack/snapshot-spaces pull request #113
Opened 2020-09-26 06:05 UTC by sdoge-master

**Add space for ...**  
  
Etherscan: https://etherscan.io/address/0xb25FEda5512445Aa4e481Add71731cD0cffF18C1
CoinGecko: 
Website: https://sdoge.org/
Twitter: https://twitter.com/sdoge_master

2020-09-27 02:33 UTC, e-asia approved these changes

2020-09-27 02:33 UTC, e-asia commented on spaces/sdoge/skin.scss
> +}
To use the default theme you will want to delete skin.scss from your space folder.

2020-09-27 02:34 UTC, e-asia requested changes
To use the default theme you will want to delete skin.scss from your space folder.

2020-09-27 04:51 UTC, sdoge-master commented
> To use the default theme you will want to delete skin.scss from your space folder.

Deleted

2020-09-29 04:55 UTC, e-asia requested changes

2020-09-29 04:55 UTC, e-asia commented on spaces/sdoge/index.json
> +  "token": "0xb25FEda5512445Aa4e481Add71731cD0cffF18C1",
Something is wrong with the token, the call to query decimals() is failing. Is this a standard ERC20 token?

2020-09-29 06:07 UTC, sdoge-master commented on spaces/sdoge/index.json
> +  "token": "0xb25FEda5512445Aa4e481Add71731cD0cffF18C1",
I've tested, no problem.

2020-09-29 06:08 UTC, sdoge-master commented on spaces/sdoge/index.json
> +  "token": "0xb25FEda5512445Aa4e481Add71731cD0cffF18C1",
FYI, forked from SUSHI.

2020-09-30 01:34 UTC, e-asia approved these changes

2020-09-30 02:24 UTC, merged