Add Y3D space
bonustrack/snapshot-spaces pull request #115
Opened 2020-09-26 15:20 UTC by guanchao71

**Add space for Y3D**  
  
Etherscan: https://etherscan.io/address/0xc7fd9ae2cf8542d71186877e21107e1f3a0b55ef  
Website: https://y3d.finance/y3d/ycrv/
Twitter: https://twitter.com/Y3dScam

2020-09-27 02:36 UTC, e-asia requested changes

2020-09-27 02:36 UTC, e-asia commented on spaces/y3d/skin.scss
> +.name {
The css selector should similar to the space key.
```suggestion
.y3d {
```

2020-09-27 04:23 UTC, guanchao71 commented on spaces/y3d/skin.scss
> +.name {
I have completed the modification

2020-09-28 11:31 UTC, lychees commented
@e-asia Kindly ping.

2020-09-29 04:56 UTC, e-asia requested changes

2020-09-29 04:56 UTC, e-asia commented on spaces/y3d/index.json
> +  "key": "Y3D",
The key of your space must also be the folder name and skin class name.
```suggestion
  "key": "y3d",
```

2020-09-29 12:05 UTC, guanchao71 commented on spaces/y3d/index.json
> +  "key": "Y3D",
I am too careless

2020-09-30 01:47 UTC, e-asia approved these changes

2020-09-30 02:24 UTC, merged