SpaceSwap Project
bonustrack/snapshot-spaces pull request #123
Opened 2020-09-28 11:27 UTC by lastmohicans

**Add space for SpaceSwap**  
  
Etherscan: https://etherscan.io/address/0x80c8c3dcfb854f9542567c8dac3f44d709ebc1de
Website: https://https://spaceswap.app/
Twitter: https://twitter.com/spaceswapdefi

2020-09-29 04:05 UTC, e-asia requested changes

2020-09-29 04:05 UTC, e-asia commented on spaces/spaceswap/skin.scss
> +.name {
The css selector should similar to the space key.
```suggestion
.spaceswap {
```

2020-09-30 10:53 UTC, PillarDevelopment commented on spaces/spaceswap/skin.scss
> +.name {
dear e-asia - I fixed this

2020-09-30 10:53 UTC, PillarDevelopment commented on spaces/spaceswap/skin.scss
> +.name {
please, merge

2020-09-30 15:09 UTC, e-asia approved these changes

2020-09-30 15:19 UTC, merged