Add CAPT space
bonustrack/snapshot-spaces pull request #124
Opened 2020-09-28 15:06 UTC by malkevych

**Add space for ...**  
  
Etherscan: https://etherscan.io/address/0x4de25f080e02e8b3fdd450f0b2b9ed22c7e6cf0a
Website: http://captainbitcoin.io
Twitter: https://twitter.com/capt_bitcoin

2020-09-29 04:06 UTC, e-asia requested changes

2020-09-29 04:06 UTC, e-asia commented on spaces/captain/skin.scss
> +}
To use the default theme you will want to delete skin.scss from your space folder.

2020-09-29 10:16 UTC, malkevych commented on spaces/captain/skin.scss
> +}
done

2020-09-30 01:43 UTC, e-asia approved these changes

2020-09-30 02:24 UTC, merged