Add UNICOPE space
bonustrack/snapshot-spaces pull request #131
Opened 2020-09-29 01:40 UTC by copejak

Add space for UNICOPE  

Etherscan: https://etherscan.io/token/0xc5074d5964de8b8157bf6d4f4846df9bc415fddf
CoinGecko: pending
Website: https://www.unicope.app/
Twitter: https://twitter.com/CopeJak

2020-09-29 04:12 UTC, e-asia requested changes

2020-09-29 04:12 UTC, e-asia commented on spaces/unicope/skin.scss
> +  }
Please use only theme variables. No extra custom styles are allowed.

2020-09-29 04:33 UTC, copejak commented on spaces/unicope/skin.scss
> +  }
ok thx, i just deleted it, ill just use the default for now. thx.

2020-09-30 01:27 UTC, e-asia requested changes

2020-09-30 01:27 UTC, e-asia commented on spaces/unicope/index.json
> +}
There is an indentation problem on that file. Please clean it.
```suggestion
  "invalid": []
}
```

2020-09-30 04:33 UTC, copejak commented on spaces/unicope/index.json
> +}
fixed

2020-09-30 14:54 UTC, e-asia approved these changes

2020-09-30 15:19 UTC, merged