Edit invalid proposal ids
bonustrack/snapshot-spaces pull request #132
Opened 2020-09-29 03:51 UTC by aisinoluhua

Edit invalid proposal ids

2020-09-29 05:12 UTC, e-asia approved these changes

2020-09-29 15:51 UTC, bonustrack commented on spaces/golff/index.json
> +  "strategies": [
You dont need this strategy, you have the same one setup already by default.

2020-09-30 15:17 UTC, e-asia requested changes

2020-09-30 15:17 UTC, e-asia commented on spaces/golff/index.json
> +  "strategies": [
@aisinoluhua Please remove or modify your strategy to valid your PR. Thank you.

2020-10-07 12:22 UTC, e-asia commented
Closing this PR for now, feel free to open it again once you've done the changes.

2020-10-07 12:22 UTC, closed without merging