add CREAM space
bonustrack/snapshot-spaces pull request #137
Opened 2020-09-29 18:26 UTC by cslarson

**Add space for CREAM**  
  
Etherscan: https://etherscan.io/address/0x2ba592F78dB6436527729929AAf6c908497cB200  
CoinGecko: https://www.coingecko.com/en/coins/cream 
Website: https://cream.finance 
Twitter: https://twitter.com/CreamdotFinance

2020-09-29 18:46 UTC, e-asia requested changes

2020-09-29 18:46 UTC, e-asia commented on spaces/cream/skin.scss
> +}
To use the default theme you will want to delete skin.scss from your space folder.

2020-09-29 18:54 UTC, cslarson commented on spaces/cream/skin.scss
> +}
doh! have removed now. thanks

2020-09-30 02:11 UTC, e-asia approved these changes

2020-09-30 02:23 UTC, merged