Add LEX space
bonustrack/snapshot-spaces pull request #145
Opened 2020-09-30 17:23 UTC by Ro5s

**Add space for LexDAO Engineering - $LEX Token**  
  
Etherscan: https://etherscan.io/address/0xA5C5C8Af327248c4c2dce810a3d3Cffb8C4F66ab#code
Website: http://lexdao.org/
Twitter: https://twitter.com/lex_DAO

2020-10-01 02:19 UTC, e-asia requested changes

2020-10-01 02:19 UTC, e-asia commented on spaces/lex/skin.scss
> +}
To use the default theme you will want to delete skin.scss from your space folder.

2020-10-01 02:21 UTC, Ro5s commented on spaces/lex/skin.scss
> +}
oh, thanks for clarification! Will delete file.

2020-10-01 16:06 UTC, Ro5s commented
thanks for the review @e-asia. I have removed the extra skin.scss file in order to get the default space theme.

2020-10-02 13:08 UTC, e-asia requested changes

2020-10-02 13:08 UTC, e-asia commented on spaces/lex/index.json
> +  "key": "$LEX",
The key will be the url and we want it all in lowercase and without special characters. Please modify the value of the key by something like `lex`. Thank you.
```suggestion
  "key": "lex",
```

2020-10-02 13:34 UTC, Ro5s commented
ah, thanks for that catch @e-asia . I have committed your suggested change for url.

2020-10-02 13:40 UTC, e-asia approved these changes

2020-10-02 13:44 UTC, merged