Add Sogur space
bonustrack/snapshot-spaces pull request #154
Opened 2020-10-01 09:02 UTC by ronsabo

**Add space for ...**  
  
Etherscan: https://etherscan.io/address/0xaea8e1b6cb5c05d1dac618551c76bcd578ea3524 
CoinGecko: https://www.coingecko.com/en/coins/sogur
Website: https://www.sogur.com
Twitter: https://twitter.com/sogurcurrency

2020-10-01 14:17 UTC, ronsabo commented on spaces/Sogur/index.json
> +  "min": 10,
The minimal balance should be 10 full units (i.e taking into account the 18 decimals). I am not sure if this value should be 10 or 10000000000000000000 so adding the  other option as a suggestion:
```suggestion
  "min": 1010000000000000000000,
```

2020-10-01 14:44 UTC, bonustrack commented on spaces/Sogur/index.json
> +  "min": 10,
It should be 10

2020-10-02 13:04 UTC, e-asia requested changes

2020-10-02 13:04 UTC, e-asia commented on spaces/Sogur/index.json
> +  "key": "Sogur",
The key will be the url and we want it all in lowercase. Please modify the value of the key by something like `sogur`. Thank you.
```suggestion
  "key": "sogur",
```

2020-10-02 13:04 UTC, e-asia commented on spaces/Sogur/index.json
> +  "key": "Sogur",
The space directory should be in lowercase too. `/spaces/sogur`

2020-10-03 05:13 UTC, ronsabo commented
All requested changes are done. 
Please review it again.

Thanks!

2020-10-03 05:14 UTC, ronsabo commented on spaces/Sogur/index.json
> +  "key": "Sogur",
done

2020-10-03 11:57 UTC, e-asia requested changes
The images file size should not exceed 50KB. Please reduce their weight.

2020-10-03 14:48 UTC, ronsabo reviewed
reduced image size

2020-10-04 04:04 UTC, e-asia approved these changes

2020-10-05 04:55 UTC, e-asia commented on spaces/sogur/index.json
> +    }]
Does this 2 tokens have the same values? Because if not it could cause troubleshooting.

2020-10-05 07:48 UTC, ronsabo commented on spaces/sogur/index.json
> +    }]
Their initial price was the same.

SGR in listed in few exchanges and thus have a clear price. 
SGN was only sold to our investors, its supply is limited and it has no operating secondary market. 

The rules of our governance system set that both tokens carry the same voting power.

2020-10-05 11:32 UTC, e-asia commented on spaces/sogur/index.json
> +    }]
Maybe you should change the base symbol with something more relevant since it will count both SGR and SGN at the same value. I recommend use the symbol "SGR+SGN"

2020-10-06 08:15 UTC, ronsabo commented on spaces/sogur/index.json
> +  "symbol": "SGR",
Adding indication that SGN token holders can also vote, following @e-asia's comment
```suggestion
  "symbol": "SGR+SGN",
```

2020-10-06 08:16 UTC, ronsabo commented on spaces/sogur/index.json
> +    }]
OK, I have added such a suggested change.

2020-10-06 13:12 UTC, e-asia commented on spaces/sogur/index.json
> +  "symbol": "SGR",
Could you commit the change, i cant't applied the suggestion. Thank you.

2020-10-06 13:47 UTC, ronsabo commented on spaces/sogur/index.json
> +  "symbol": "SGR",
done

2020-10-07 01:32 UTC, e-asia approved these changes

2020-10-07 02:10 UTC, merged