Rinkeby; Update domains.json for oaklanddao
bonustrack/snapshot-spaces pull request #174
Opened 2020-10-04 15:52 UTC by natenatesoo

**Add space for ...**  
  
Etherscan: https://etherscan.io/address/...  
CoinGecko: https://www.coingecko.com/en/coins/...  
Website: https://...  
Twitter: https://twitter.com/...

2020-10-05 04:39 UTC, e-asia requested changes

2020-10-05 04:39 UTC, e-asia commented on spaces/domains.json
> +}
There is a problem with `domains.json`, you need to add your domain a the end of the list and seems that you add only your domain. Please pull again to get full `domains.json` file.

2020-10-05 05:08 UTC, natenatesoo commented on spaces/domains.json
> +}
Apologies, the domains.json file under the Rinkeby branch was completely empty.  I know that you have DAI and Aragon within the homepage.json, but they aren't listed within domains.json.  Should I add my domain to the domains.json under the Master branch?

Once again, sorry if I have any misunderstandings. Thank you for your time and attention.

2020-10-05 10:26 UTC, e-asia commented on spaces/domains.json
> +}
You were right but we have changed the homepage and there are now all spaces all protocol together.

2020-10-05 11:32 UTC, e-asia requested changes

2020-10-07 05:33 UTC, e-asia approved these changes

2020-10-07 05:36 UTC, merged