Add SLEEP space
bonustrack/snapshot-spaces pull request #175
Opened 2020-10-05 01:02 UTC by aEdrR

Add space for SLEEP
  
Etherscan: https://etherscan.io/address/0x3C1EE45e11E90fC20427BE5e6Db5FEe557f1E07f

2020-10-05 04:49 UTC, e-asia requested changes

2020-10-05 04:49 UTC, e-asia commented on spaces/sleeping/skin.scss
> +.name {
The css selector should similar to the space key.
```suggestion
.sleeping {
```

2020-10-05 17:20 UTC, aEdrR commented on spaces/sleeping/skin.scss
> +.name {
Thank you for the quick review!

2020-10-06 12:04 UTC, e-asia approved these changes

2020-10-06 12:23 UTC, merged