feat: Add CAPY space
bonustrack/snapshot-spaces pull request #188
Opened 2020-10-05 20:24 UTC by magicball342

**Add space for CAPY**  
  
Etherscan: https://etherscan.io/address/0x367B072D50ac465bA47Ab474c6d381BfC0e45F86#code
Website: https://apy.center
Twitter: https://twitter.com/ApyCenter

2020-10-06 12:07 UTC, e-asia requested changes

2020-10-06 12:07 UTC, e-asia commented on spaces/capy/skin.scss
> +.name {
The css selector should similar to the space key.
```suggestion
.capy {
```

2020-10-06 12:58 UTC, magicball342 commented on spaces/capy/skin.scss
> +.name {
thanks for the feedback. selector fixed.

2020-10-07 01:34 UTC, e-asia approved these changes

2020-10-07 02:10 UTC, merged