Create metamorphpro
bonustrack/snapshot-spaces pull request #190
Opened 2020-10-06 12:37 UTC by danlewcom

**Add space for ...**  
  
Etherscan: https://etherscan.io/token/0xfef3884b603c33ef8ed4183346e093a173c94da6
CoinGecko: https://www.coingecko.com/en/coins/metamorph
Website: https://metamorph.pro
Twitter: https://twitter.com/metamorphpro
![logo](https://user-images.githubusercontent.com/13414700/95202108-38d10780-0824-11eb-8dcc-6b9e97404040.png)
![space](https://user-images.githubusercontent.com/13414700/95202230-60c06b00-0824-11eb-9a27-de4f7c313b91.png)

2020-10-06 13:23 UTC, e-asia requested changes

2020-10-06 13:23 UTC, e-asia commented on spaces/metamorphpro
> +}
You should reformat code and delete comments.
Both images `logo.png` and `space.png` should be in your `spaces/metamorphpro` directory and should not exceed 50kb.
Thank you.

2020-10-07 01:52 UTC, e-asia commented on spaces/metamorphpro
> +}
Your images still missing in your PR.

2020-10-07 09:19 UTC, danlewcom reviewed
Please approve, I have added both space.png and logo.png

2020-10-07 09:19 UTC, danlewcom commented on spaces/metamorphpro
> +}
![space](https://user-images.githubusercontent.com/13414700/95312111-dc2c2600-08d1-11eb-8445-0202a4772a63.png)

2020-10-07 11:45 UTC, e-asia commented on spaces/metamorphpro
> +}
You shouldn’t upload your files anywhere but add it with git command line and commit it in your Pull Request.
Something like:
`
git add spaces/metamorphpro/logo.png spaces/metamorphpro/space.png
git commit -m "add spaces/metamorphpro images"
git push
`

2020-10-13 14:16 UTC, e-asia commented
We have updated all the spaces. You have to do a git pull before commit your changes again or create a new pull request.

2020-10-13 14:16 UTC, closed without merging