add GFIN space
bonustrack/snapshot-spaces pull request #195
Opened 2020-10-07 03:50 UTC by ayogatot

**Add space for GFIN**  
  
Etherscan: https://etherscan.io/address/0x21E19121e1360e09AA1F810280c97A87b85d1069
Website: coming soon 🤩
Twitter: coming soon 🤩

2020-10-07 11:19 UTC, e-asia requested changes

2020-10-07 11:19 UTC, e-asia commented on spaces/griffin/index.json
> +}
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-10-07 11:30 UTC, ayogatot commented on spaces/griffin/index.json
> +}
Ok thanks, i've already updated it.

2020-10-08 01:36 UTC, e-asia approved these changes

2020-10-08 01:55 UTC, merged