add YKZ space
bonustrack/snapshot-spaces pull request #196
Opened 2020-10-07 03:52 UTC by dmitry-morgachev

Add space for YKZ
  
Etherscan: https://etherscan.io/address/0x87047986e8e4961c11d2edcd94285e3a1331d97b
CoinGecko: https://www.coingecko.com/en/coins/yakuza-dfo
Website: https://www.ykz.network/
Twitter: https://twitter.com/yakuza_dfo

2020-10-07 11:06 UTC, e-asia requested changes

2020-10-07 11:06 UTC, e-asia commented on spaces/yakuza/skin.scss
> +}
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.

![image](https://user-images.githubusercontent.com/8545464/95323076-c285e100-08c7-11eb-9475-9f1a06ef1d3a.png)

2020-10-07 18:50 UTC, dmitry-morgachev commented on spaces/yakuza/skin.scss
> +}
@e-asia thank you, reviewed skin. Should be better now.

2020-10-08 01:46 UTC, e-asia requested changes

2020-10-08 01:46 UTC, e-asia commented on spaces/yakuza/skin.scss
> +}
You still have the Publish button unreadable. 
![image](https://user-images.githubusercontent.com/8545464/95405648-965b7600-0942-11eb-86e7-dc4e0b45e070.png)

2020-10-08 04:01 UTC, dmitry-morgachev commented on spaces/yakuza/skin.scss
> +}
Missed link-color in skin, fixed

2020-10-08 05:34 UTC, e-asia approved these changes

2020-10-08 05:47 UTC, merged