Add OAKM space
bonustrack/snapshot-spaces pull request #198
Opened 2020-10-07 09:38 UTC by natenatesoo

**Add space for OaklandDAO**  
  
Etherscan: https://etherscan.io/address/...  
CoinGecko: https://www.coingecko.com/en/coins/...  
Website: https://...  
Twitter: https://twitter.com/...

2020-10-07 11:30 UTC, e-asia requested changes

2020-10-07 11:30 UTC, e-asia commented on spaces/domains.json
>  }
Please remove `domains.json` file from your PR. You forgot the key indeed and we already merged it live with a fix since your last PR #197 .

2020-10-08 01:52 UTC, e-asia requested changes
Sorry i think this will delete the file. The `domains.json` should not appear in your PR. Could you clear it? Thank you

2020-10-08 18:04 UTC, natenatesoo commented
Sorry about that.  I'm just beginning my Developer Education, and github is
something I'm still learning.  Thank you for your patience and all the help
you have been providing.   I'm still sure on how to modify an already
initiated PR.  Is it easier to close a flawed PR and create a new one?

Seriously, thank you once again.  I'm really excited about utilizing
snapshot for this non-profit community DAO.

On Wed, Oct 7, 2020 at 6:52 PM Jeremy <notifications@github.com> wrote:

> *@e-asia* requested changes on this pull request.
>
> Sorry i think this will delete the file. The domains.json should not
> appear in your PR. We will do it ;). Thank you
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/bonustrack/snapshot-spaces/pull/198#pullrequestreview-504377839>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK4OPFS5YLE5CJHXE4J4BI3SJULNDANCNFSM4SHEYXBA>
> .
>

2020-10-09 01:36 UTC, e-asia commented
@natenatesoo Yes the simplest way for you would be to close this PR et recommit in a new one only your 4 space files. Notify me when it's done then i'll merge it ;) Good luck.

2020-10-09 03:47 UTC, closed without merging