pool3 pool4 mefi can also vote
bonustrack/snapshot-spaces pull request #203
Opened 2020-10-08 02:27 UTC by jin10086

2020-10-08 05:16 UTC, e-asia requested changes

2020-10-08 05:16 UTC, e-asia commented on spaces/dfi/index.json
> +    ["erc20-balance-of", { //poo4
JSON standard does not allow comments. Please remove them.
```suggestion
    ["erc20-balance-of", {
```

2020-10-08 05:26 UTC, jin10086 commented on spaces/dfi/index.json
> +    ["erc20-balance-of", { //poo4
done

2020-10-08 05:46 UTC, e-asia approved these changes

2020-10-08 07:45 UTC, e-asia commented on spaces/dfi/index.json
> +    ["erc20-balance-of", { //poo4
The UI will break currently if there is more than 2 strategies, does yours strategies have all the same value?

2020-10-08 09:09 UTC, jin10086 commented on spaces/dfi/index.json
> +    ["erc20-balance-of", { //poo4
use proxy vote contract https://etherscan.io/address/0x266cA21f966D93F5580E20b55ef66C8320E4760E#code

2020-10-08 12:42 UTC, e-asia approved these changes

2020-10-08 13:09 UTC, e-asia commented on spaces/dfi/index.json
> +    ["erc20-balance-of", { //poo4
@jin10086 The old proposal will show new strategy result, do you valid it?

2020-10-08 13:24 UTC, jin10086 commented on spaces/dfi/index.json
> +    ["erc20-balance-of", { //poo4
@e-asia How to verify the prod? I didn't find the document

2020-10-08 15:52 UTC, e-asia commented on spaces/dfi/index.json
> +    ["erc20-balance-of", { //poo4
Look the difference between live and new strategies.
![image](https://user-images.githubusercontent.com/8545464/95483049-f8ef5900-09b8-11eb-8288-bc87cb1a733f.png)
![image](https://user-images.githubusercontent.com/8545464/95483071-fdb40d00-09b8-11eb-975a-3843fe1b2f0d.png)

2020-10-09 00:34 UTC, jin10086 commented on spaces/dfi/index.json
> +    ["erc20-balance-of", { //poo4
Thank you, the new strategy will not affect.

2020-10-09 01:21 UTC, merged