Add 'swarm' space
bonustrack/snapshot-spaces pull request #210
Opened 2020-10-08 14:24 UTC by bowsernet

**Add space for Swarm Network**  
  
Etherscan: https://etherscan.io/address/0x3505f494c3f0fed0b594e01fa41dd3967645ca39
CoinGecko: https://www.coingecko.com/en/coins/swarm-fund 
Website: https://swarmnetwork.org
Twitter: https://twitter.com/SWARM

2020-10-08 15:42 UTC, e-asia requested changes

2020-10-08 15:42 UTC, e-asia commented on spaces/swarm/skin.scss
> +.name {
The css selector should similar to the space key.
```suggestion
.swarm {
```

2020-10-08 15:57 UTC, bowsernet commented on spaces/swarm/skin.scss
> +.name {
fixed, sorry, I knew and still I forgot

2020-10-09 01:27 UTC, e-asia approved these changes

2020-10-09 01:55 UTC, merged