Add EXNG space
bonustrack/snapshot-spaces pull request #211
Opened 2020-10-08 14:57 UTC by exnetworkd3v

Add space for ...  
  
Etherscan: https://etherscan.io/token/0xD6c67B93a7b248dF608a653d82a100556144c5DA  
CoinGecko: https://www.coingecko.com/en/coins/exnetwork-token  
Website: https://exnetwork.community
Twitter: https://twitter.com/exncapital

2020-10-08 15:44 UTC, e-asia requested changes

2020-10-08 15:44 UTC, e-asia commented on spaces/exnetwork/skin.scss
> +}
To use the default theme you will want to delete skin.scss from your space folder.

2020-10-08 16:00 UTC, exnetworkd3v commented on spaces/exnetwork/skin.scss
> +}
Is it okay if we replace '.name' with our key?

2020-10-09 01:31 UTC, e-asia approved these changes

2020-10-09 01:55 UTC, merged