Update ton space
bonustrack/snapshot-spaces pull request #212
Opened 2020-10-08 19:34 UTC by toozwu

**Add space for ...**  
  
Etherscan: https://etherscan.io/address/...  
CoinGecko: https://www.coingecko.com/en/coins/...  
Website: https://...  
Twitter: https://twitter.com/...

2020-10-09 01:41 UTC, e-asia requested changes

2020-10-09 01:41 UTC, e-asia commented on spaces/ton/index.json
> +}
There is a conflict in your PR, can you resolve it?

2020-10-11 05:52 UTC, toozwu commented on spaces/ton/index.json
> +}
Hi, what's conflict? I just want update "defaultView".

2020-10-12 09:46 UTC, toozwu commented on spaces/ton/index.json
> +}
Hi e-asia ^_^

2020-10-13 14:19 UTC, closed without merging