Add ZETA space
bonustrack/snapshot-spaces pull request #235
Opened 2020-10-12 05:28 UTC by bannplayer

Etherscan: 
https://etherscan.io/address/0x6226392cf37FA359Bfa58C9Cb3d66a5f96083eB6
https://etherscan.io/address/0x3446598b93A41543a470193D82E8C01a7f131fff

Website: https://www.zetaportfolio.com
Twitter: https://twitter.com/ZETA_Portfolio

2020-10-12 13:41 UTC, e-asia requested changes

2020-10-12 13:41 UTC, e-asia commented on skins/zeta.scss
> +}
If you use the default theme you will need to delete the scss file.

2020-10-12 13:41 UTC, e-asia commented on spaces/zeta/index.json
> +  "skin": "zeta"
If you use the default theme you will need to remove the skin field.

2020-10-13 02:31 UTC, bannplayer commented
Fixed color

2020-10-13 13:45 UTC, e-asia requested changes

2020-10-13 14:26 UTC, e-asia commented on spaces/zeta/index.json
> +  ],
Does the 2 token have the same $ value? Otherwise thats probably not something we recommend to do for strategies. Tell me if you want to validate your strategies?

2020-10-14 02:07 UTC, bannplayer commented on spaces/zeta/index.json
> +  ],
It is almost same value, sZETA is staked ZETA pegged 1 : 1. And the purpose of two strategies is that we wanted users to participate with sZETA and ZETA both.

2020-10-14 03:52 UTC, e-asia commented on spaces/zeta/index.json
> +  ],
Looks like you've packed a lot of files into your PR. Maybe you want to try to correct it or close this PR and start from scratch to make a clean PR before merging.
https://github.com/bonustrack/snapshot-spaces/pull/235/files

2020-10-14 04:19 UTC, bannplayer commented on spaces/zeta/index.json
> +  ],
Ok then will start from scratch again, close this and make a clean PR

2020-10-14 04:20 UTC, bannplayer commented
Erased key and address field

2020-10-14 04:20 UTC, closed without merging