moonswap submit
bonustrack/snapshot-spaces pull request #34
Opened 2020-09-13 15:08 UTC by jhlovesky

2020-09-13 15:30 UTC, huangtao163 requested changes
add moonswap

2020-09-13 15:31 UTC, huangtao163 commented
add space moonswap

2020-09-14 03:02 UTC, e-asia commented on spaces/moonswap/skin.scss
> +}
Remove the skin.scss file to use the default theme.

2020-09-19 09:37 UTC, huangtao163 commented on spaces/moonswap/skin.scss
> +}
The update has been submitted, please preview

2020-09-20 08:04 UTC, huangtao163 commented
The update has been submitted, please preview

2020-09-20 08:05 UTC, huangtao163 requested changes
The update has been submitted, please preview

2020-09-21 03:15 UTC, e-asia requested changes

2020-09-21 03:15 UTC, e-asia commented on spaces/moonswap/index.json
> +}
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-21 04:59 UTC, huangtao163 requested changes
parameters Chainid and decimals added

2020-09-22 02:29 UTC, e-asia approved these changes

2020-09-22 14:05 UTC, merged