add ADEL space
bonustrack/snapshot-spaces pull request #45
Opened 2020-09-15 09:08 UTC by AlexanderMazaletskiy

2020-09-15 13:34 UTC, bonustrack commented on spaces/akropolis-delphi/index.json
> +    ["balancer", {
If you want to use BPT to score proposal results that's not the way to do it. You could count ADEL and ADEL inside BPT pools if you want. You will need to use erc20BalanceOf + balancer strategies with `0x94d863173EE77439E4292284fF13fAD54b3BA182` as address on both strategies

2020-09-16 08:24 UTC, AlexanderMazaletskiy commented
Our idea is that tokens are put in proportions to the user in the Balancer Pool. And the tokens received by BPT are already participating in the voting.

2020-09-16 08:24 UTC, AlexanderMazaletskiy commented
@bonustrack Please check

2020-09-17 04:25 UTC, e-asia commented
@AlexanderMazaletskiy 
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
![image](https://user-images.githubusercontent.com/8545464/93419945-3db33300-f8d8-11ea-8290-a9961d782718.png)

2020-09-17 09:48 UTC, AlexanderMazaletskiy commented
@e-asia Please, check

2020-09-18 01:46 UTC, e-asia approved these changes

2020-09-18 04:29 UTC, bonustrack commented on spaces/akropolis-delphi/index.json
> +  "strategies": [
If you want to use the BPT you should remove strategies array, and change `address` and `token` to the BPT address. Also i recommend to use symbol "ADEL-AKRO"

2020-09-18 06:19 UTC, AlexanderMazaletskiy commented on spaces/akropolis-delphi/index.json
> +    ["balancer", {
@bonustrack @e-asia Please, check

2020-09-23 06:04 UTC, e-asia requested changes

2020-09-23 06:04 UTC, e-asia commented on spaces/akropolis-delphi/index.json
> +}
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-23 11:33 UTC, e-asia requested changes
The images file size should not exceed 50KB. Please reduce their weight.

2020-09-23 11:33 UTC, e-asia commented on spaces/homepage.json
> +  "akropolis-delphi"
To be approved, your space will need to be active with few proposals and significant participation rate.

2020-09-23 11:35 UTC, e-asia commented
@AlexanderMazaletskiy You should also delete `logo1.png` to add only `logo.png`. Thank you.

2020-09-23 13:05 UTC, in19farkt commented on spaces/homepage.json
> +  "akropolis-delphi"
Fixed

2020-09-23 13:07 UTC, in19farkt commented
> You should also delete logo1.png to add only logo.png. Thank you.
@e-asia But `logo1.png` needed for the second strategy, or not?

2020-09-23 13:11 UTC, bonustrack commented
@AlexanderMazaletskiy Yes you should keep that file for the second strategy.

2020-09-23 13:17 UTC, in19farkt commented
> The images file size should not exceed 50KB. Please reduce their weight.

Fixed.

2020-09-23 13:34 UTC, AlexanderMazaletskiy commented
For strategy, you need check this PR https://github.com/bonustrack/snapshot.js/pull/4

2020-09-23 20:20 UTC, merged