Add REB2 space
bonustrack/snapshot-spaces pull request #56
Opened 2020-09-17 05:59 UTC by cch1985

2020-09-18 01:32 UTC, e-asia commented on spaces/reb2/skin.scss
> +}
To use the default theme you will want to delete skin.scss from your space folder.

2020-09-19 20:50 UTC, cch1985 commented on spaces/reb2/skin.scss
> +}
Done.

2020-09-19 20:51 UTC, cch1985 commented
Just deleted the skin.scss. Everything else good to go?

2020-09-20 09:26 UTC, e-asia requested changes

2020-09-20 09:26 UTC, e-asia commented on spaces/reb2/index.json
> +  "token": "0x87F5F9eBE40786D49D35E1B5997b07cCAA8ADbFF",
Something is wrong with the token, the call to query decimals() is failing. Is this a standard ERC20 token?

2020-09-20 16:25 UTC, cch1985 commented on spaces/reb2/index.json
> +  "token": "0x87F5F9eBE40786D49D35E1B5997b07cCAA8ADbFF",
> Something is wrong with the token, the call to query decimals() is failing. Is this a standard ERC20 token?

Yeah it's a standard ERC20. Perhaps because it's a 9 decimal token?

2020-09-21 01:41 UTC, e-asia requested changes

2020-09-21 01:41 UTC, e-asia commented on spaces/reb2/index.json
> +  "symbol": "REB2"
You miss a comma ',' at the end of symbol line. 
```suggestion
  "symbol": "REB2",
```

2020-09-21 03:34 UTC, e-asia requested changes

2020-09-21 03:34 UTC, e-asia commented on spaces/reb2/index.json
> +  "token": "0x87F5F9eBE40786D49D35E1B5997b07cCAA8ADbFF",
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-21 03:42 UTC, cch1985 commented on spaces/reb2/index.json
> +  "token": "0x87F5F9eBE40786D49D35E1B5997b07cCAA8ADbFF",
Done. Let me know if it's good!

2020-09-22 02:06 UTC, e-asia approved these changes

2020-09-22 14:04 UTC, merged