Request to add BFT to Spaces
bonustrack/snapshot-spaces pull request #58
Opened 2020-09-17 07:57 UTC by BFTFinance

2020-09-18 01:39 UTC, e-asia commented on spaces/bft/index.json
> +  "name": "Berkshire.Finance",
Can you choose a shorter name? This will break the interface on a small screen otherwise.

2020-09-18 06:13 UTC, BFTFinance commented on spaces/bft/index.json
> +  "name": "Berkshire.Finance",
Yes, sorry about that just made the change. -Thank you

2020-09-20 09:07 UTC, e-asia requested changes

2020-09-20 09:07 UTC, e-asia commented on spaces/bft/index.json
> +  "token": "0x1ec128C3D3F256Cad161cf7A3F148f47F03f1D36",
Something is wrong with the token, the call to query decimals() is failing. Is this a standard ERC20 token?

2020-09-21 03:24 UTC, e-asia requested changes

2020-09-21 03:24 UTC, e-asia commented on spaces/bft/index.json
> +}
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-21 09:35 UTC, BFTFinance commented on spaces/bft/index.json
> +}
Thank you, have made the updates based on the format.

2020-09-22 02:48 UTC, e-asia requested changes

2020-09-22 02:48 UTC, e-asia commented on spaces/bft/index.json
> +  "token": "0x1ec128C3D3F256Cad161cf7A3F148f47F03f1D36",
@BFTFinance there is always a problem with the token.

2020-10-01 03:03 UTC, e-asia commented
Closing this PR for now, feel free to open it again once you've done the changes.

2020-10-01 03:03 UTC, closed without merging