Edit JIAOZI space
bonustrack/snapshot-spaces pull request #59
Opened 2020-09-17 19:40 UTC by nightg0at

2020-09-18 01:51 UTC, e-asia commented
@nightg0at You will want to add logo.png and space.png files.
https://docs.snapshot.page/guides/create-a-space#4-add-a-logo-and-space-images

2020-09-18 08:07 UTC, nightg0at commented
Hi @e-asia, the files you mention are already in your repo (see #39). This is an edit not a new space.

2020-09-20 08:57 UTC, e-asia approved these changes

2020-09-20 08:58 UTC, e-asia commented
Hi @nightg0at. Yes you are right, sorry my bad, reviewed and approved.

2020-09-21 03:17 UTC, e-asia requested changes

2020-09-21 03:17 UTC, e-asia commented on spaces/jiaozi/index.json
> +}
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-10-01 03:03 UTC, e-asia commented
Closing this PR for now, feel free to open it again once you've done the changes.

2020-10-01 03:03 UTC, closed without merging