change LONGPOWER contract address
bonustrack/snapshot-spaces pull request #61
Opened 2020-09-18 04:26 UTC by psyduckasa

2020-09-20 09:01 UTC, e-asia approved these changes

2020-09-21 03:22 UTC, e-asia requested changes

2020-09-21 03:22 UTC, e-asia commented on spaces/long/index.json
>    ],
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-22 04:23 UTC, psyduckasa commented on spaces/long/index.json
>    ],
Done. Added chainId and decimals parameters. @e-asia

2020-09-22 11:49 UTC, e-asia approved these changes

2020-09-23 11:59 UTC, e-asia commented on spaces/long/index.json
>    ],
@psyduckasa If you change the base token address your old proposals will not be visible anymore under your space, are you sure you want to go forward with this?

2020-09-23 14:42 UTC, psyduckasa commented on spaces/long/index.json
>    ],
@e-asia Yes, it's OK, new LONGPOWER contract fixes incorrect pool id.

2020-09-24 04:15 UTC, psyduckasa commented
@e-asia Looks like the code has been manually merged in?
https://github.com/bonustrack/snapshot-spaces/blob/master/spaces/long/index.json

2020-09-24 12:45 UTC, merged