Add CREED space
bonustrack/snapshot-spaces pull request #62
Opened 2020-09-18 06:52 UTC by creedev

2020-09-20 08:17 UTC, e-asia approved these changes

2020-09-21 03:16 UTC, e-asia requested changes

2020-09-21 03:16 UTC, e-asia commented on spaces/creed/index.json
> +}
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-21 04:07 UTC, creedev commented
@e-asia Can you please review once now. Thanks.

2020-09-22 02:26 UTC, e-asia approved these changes

2020-09-22 14:03 UTC, merged