Add PCT space
bonustrack/snapshot-spaces pull request #63
Opened 2020-09-18 07:24 UTC by percent-finance

2020-09-20 08:19 UTC, e-asia commented on spaces/percent/skin.scss
> +}
To use the default theme you will want to delete skin.scss from your space folder.

2020-09-20 11:19 UTC, percent-finance commented
@e-asia Thanks! The skin.scss is deleted now! Please check again!

2020-09-21 03:24 UTC, e-asia requested changes

2020-09-21 03:24 UTC, e-asia commented on spaces/percent/index.json
> +}
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-22 10:07 UTC, percent-finance commented
@e-asia Thanks! I've added the 2 new fields. I've also changed the symbol and address, so that it now supports quadratic voting. Please review again.

2020-09-23 05:23 UTC, e-asia approved these changes

2020-09-23 06:52 UTC, merged