Add DEGO space
bonustrack/snapshot-spaces pull request #65
Opened 2020-09-18 09:43 UTC by dego-team

2020-09-20 08:36 UTC, e-asia reviewed
Files in the default `example` folder should not be edited. Please remove them from your pull request.

2020-09-21 03:27 UTC, e-asia requested changes

2020-09-21 03:27 UTC, e-asia commented on spaces/dego/index.json
> +}
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-21 08:46 UTC, closed without merging

2020-09-21 08:46 UTC, dego-team commented
I have add a new pull