add voting power to people who staked in sharing profit pool
bonustrack/snapshot-spaces pull request #66
Opened 2020-09-18 09:44 UTC by chrouzz

2020-09-20 08:34 UTC, bonustrack commented
@e-asia Can you check this PR again?

2020-09-20 08:40 UTC, e-asia approved these changes

2020-09-21 03:21 UTC, e-asia requested changes

2020-09-21 03:21 UTC, e-asia commented on spaces/farm/index.json
> +  ]
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-23 03:32 UTC, chrouzz commented on spaces/farm/index.json
> +  ]
I think I already have a chainId and decimals in the index.json

2020-09-23 05:37 UTC, chrouzz commented on spaces/farm/index.json
> +  ]
you mean the chainId and decimals is for the voting strategie?

2020-09-23 11:03 UTC, e-asia approved these changes

2020-09-26 13:14 UTC, merged

2020-09-26 13:57 UTC, e-asia commented
@chrouzz We merged your PR but had to update the strategy here #114. All the old proposals will have the result of the new strategy. That means a different result compared to the previous strategy.