Add 0xDollar space
bonustrack/snapshot-spaces pull request #67
Opened 2020-09-18 09:56 UTC by 0xFranklin

Add 0xDollar space to snapshot

2020-09-20 08:44 UTC, e-asia reviewed
The images file size should not exceed 50KB. Please reduce their weight.

2020-09-20 12:16 UTC, 0xFranklin commented
@e-asia I compress the png. Thx for reminding

2020-09-21 03:25 UTC, e-asia requested changes

2020-09-21 03:25 UTC, e-asia commented on spaces/0xdollar/index.json
> +}
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-21 05:48 UTC, 0xFranklin commented
@e-asia I already add chainId and decimals. Thx

2020-09-22 02:32 UTC, e-asia approved these changes

2020-09-22 14:03 UTC, merged