Add GOF space
bonustrack/snapshot-spaces pull request #71
Opened 2020-09-19 06:29 UTC by aisinoluhua

2020-09-19 06:32 UTC, aisinoluhua commented
add GOF space

2020-09-20 08:47 UTC, e-asia requested changes

2020-09-20 08:47 UTC, e-asia commented on spaces/golff/skin.scss
> +.yam {
The css selector should similar to the space key.
```suggestion
.golff {
```

2020-09-20 08:47 UTC, e-asia commented on spaces/golff/index.json
> +  "key": "gof",
The key of your space must also be the folder name and skin class name.
```suggestion
  "key": "golff",
```

2020-09-21 03:02 UTC, aisinoluhua commented
The space key and skin class name have been modified

2020-09-21 03:35 UTC, e-asia requested changes

2020-09-21 03:35 UTC, e-asia commented on spaces/golff/index.json
> +}
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-21 03:43 UTC, aisinoluhua commented on spaces/golff/index.json
> +}
> We have updated the format in `index.json`.
> Please add 2 new parameters `chainId` and `decimals`.
> You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

like this?
{
  "key": "golff",
  "symbol": "GOF",
  "name": "Golff Finance",
  "defaultView": "core",
  "address": "0x488E0369f9BC5C40C002eA7c1fe4fd01A198801c",
  "token": "0x488E0369f9BC5C40C002eA7c1fe4fd01A198801c",
  "chainId":1,
  "decimals":18,
  "core": [
    "0x424abfc7c0Defb02447D621Bf0f6eF80eD5C01fB"
  ],
  "min": 100,
  "invalid": [
    "0x424abfc7c0Defb02447D621Bf0f6eF80eD5C01fB"
  ]
}

2020-09-22 02:16 UTC, e-asia approved these changes

2020-09-22 02:16 UTC, e-asia commented on spaces/golff/index.json
> +}
@aisinoluhua Yes 👍

2020-09-22 14:02 UTC, merged