update logo.png for Dollar Protocol
bonustrack/snapshot-spaces pull request #72
Opened 2020-09-19 23:09 UTC by satoshinate

2020-09-19 23:09 UTC, satoshinate commented
@bonustrack updated Repo to match master

2020-09-20 09:28 UTC, e-asia approved these changes

2020-09-21 21:40 UTC, satoshinate commented
any update?

2020-09-22 02:50 UTC, e-asia requested changes

2020-09-22 02:50 UTC, e-asia commented on spaces/dollar-protocol/index.json
>    ],
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-22 16:24 UTC, satoshinate commented on spaces/dollar-protocol/index.json
>    ],
done

2020-09-22 16:24 UTC, satoshinate commented
@e-asia fixed now

2020-09-23 05:59 UTC, e-asia approved these changes

2020-09-23 11:58 UTC, e-asia commented
@satoshinate If you change the base token address your old proposals will not be visible anymore under your space, are you sure you want to go forward with this?

2020-09-23 13:37 UTC, satoshinate commented
@e-asia yes please - we only had 1 test proposal from before. this is now the real deal

2020-09-23 14:08 UTC, merged