ADD DEGO space
bonustrack/snapshot-spaces pull request #74
Opened 2020-09-20 12:29 UTC by dego-team

2020-09-21 03:28 UTC, e-asia requested changes

2020-09-21 03:28 UTC, e-asia commented on spaces/dego/index.json
> +}
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-21 03:28 UTC, e-asia commented on spaces/dego/skin.scss
> +}
To use the default theme you will want to delete skin.scss from your space folder.

2020-09-21 03:29 UTC, e-asia commented
@dego-team You have 2 active PR with #65. You may want to close one of them.

2020-09-21 08:59 UTC, dego-team commented
I have closed #65 and commit as your request

2020-09-22 02:35 UTC, e-asia requested changes

2020-09-22 02:35 UTC, e-asia commented on spaces/dego/index.json
> +  "decimals": 18, // Number of decimals in the token
JSON standard does not allow comments. Please remove them.

2020-09-22 04:26 UTC, dego-team commented on spaces/dego/index.json
> +  "decimals": 18, // Number of decimals in the token
sorry, I'v forgot it. I have remove them

2020-09-22 11:55 UTC, e-asia approved these changes

2020-09-22 14:01 UTC, merged