Add ROT space
bonustrack/snapshot-spaces pull request #75
Opened 2020-09-20 20:20 UTC by wallbanger1

This should be ready to go. Let me know if there are any errors. This was done at the request of Tim the founding dev for RottenSwap(ROT). https://github.com/rottenswap

2020-09-21 03:31 UTC, e-asia requested changes

2020-09-21 03:31 UTC, e-asia commented on spaces/rottenswap/index.json
> +  "key": "rotten-swap",
The key of your space must also be the folder name and skin class name.

2020-09-21 03:31 UTC, e-asia commented on spaces/rottenswap/index.json
> +}
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-21 03:49 UTC, wallbanger1 commented on spaces/rottenswap/index.json
> +}
Ok this has been updated. I didn't see those documented anywhere. It is not mentioned on ur linked docs.
![image](https://user-images.githubusercontent.com/71581829/93731628-b210ff00-fb82-11ea-93dc-d931179b835b.png)

2020-09-21 03:54 UTC, wallbanger1 commented on spaces/rottenswap/index.json
> +  "key": "rotten-swap",
Noted and fixed. I changed the folder to include the hyphen. The class name is the same as well.

2020-09-21 03:55 UTC, wallbanger1 commented
Ok I think everything is updated now. Please let me know if there are any other issues. Thanks!

2020-09-22 02:22 UTC, e-asia approved these changes

2020-09-22 14:00 UTC, merged