Edit Sake Address
bonustrack/snapshot-spaces pull request #78
Opened 2020-09-21 01:55 UTC by therealsakeswap

2020-09-21 03:35 UTC, e-asia requested changes

2020-09-21 03:35 UTC, e-asia commented on spaces/sake/index.json
>    ],
We have updated the format in `index.json`. 
Please add 2 new parameters `chainId` and `decimals`.
You can refer to the documentation that has been completed. https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-09-21 03:42 UTC, coolc4 commented on spaces/sake/index.json
>    ],
@e-asia  the new code have include the 2 new  new parameters, chainId and decimals.
Please help check and merge it,thanks

2020-09-21 03:46 UTC, therealsakeswap commented on spaces/sake/index.json
>    ],
@e-asia  the code have included the 2 new parameters chainId and decimals.
Please help to check and merge it. Thanks.

2020-09-22 02:11 UTC, e-asia approved these changes

2020-09-23 11:57 UTC, e-asia commented on spaces/sake/index.json
>    ],
@therealsakeswap If you change the base token address your old proposals will not be visible anymore under your space, are you sure you want to go forward with this?

2020-09-23 12:40 UTC, therealsakeswap commented
dear bonustrack:
Yes, I am sure I have known the proposals in old token address can't visible anymore under my space. we accept it,please help us to merge the new token address.
Thank you.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On 2020年9月23日WednesdayPM7点57分, Jeremy <notifications@github.com> wrote:

> @e-asia commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [spaces/sake/index.json](https://github.com/bonustrack/snapshot-spaces/pull/78#discussion_r493501634):
>
>>    "chainId": 1,
>    "decimals": 18,
>    "symbol": "SAKE",
>    "defaultView": "core",
> -  "address": "0x066798d9ef0833ccc719076Dab77199eCbd178b0",
> -  "token": "0x066798d9ef0833ccc719076Dab77199eCbd178b0",
> +  "address": "0x0A291AF57DEb09efd3760B8Ca7167207bcE019d6",
> +  "token": "0x0A291AF57DEb09efd3760B8Ca7167207bcE019d6",
>    "core": [
>      "0x142151D3b15b8961F2937Cf7880Bcd10c050800C"
>    ],
>
> [@therealsakeswap](https://github.com/therealsakeswap) If you change the base token address your old proposals will not be visible anymore under your space, are you sure you want to go forward with this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, [view it on GitHub](https://github.com/bonustrack/snapshot-spaces/pull/78#discussion_r493501634), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AQ3K4KXLE2YRGOIWFL67A4LSHHPCFANCNFSM4RT7THBQ).

2020-09-23 14:08 UTC, merged