Add YAX space
bonustrack/snapshot-spaces pull request #84
Opened 2020-09-22 02:48 UTC by alexgausman

2020-09-23 05:18 UTC, e-asia requested changes

2020-09-23 05:18 UTC, e-asia commented on spaces/yaxis/skin.scss
> +  }
Please use only theme variables. No extra custom styles are allowed.

2020-09-24 19:40 UTC, alexgausman commented
Updated. Thanks!

2020-09-25 15:27 UTC, e-asia approved these changes

2020-09-26 13:06 UTC, merged