Add MTA space
bonustrack/snapshot-spaces pull request #89
Opened 2020-09-22 16:17 UTC by dereksilva

2020-09-23 05:36 UTC, e-asia requested changes

2020-09-23 05:36 UTC, e-asia commented on spaces/mstable/skin.scss
> +  --primary-color: ##1065E0;
You have 2 # in the hexadecimal color.
```suggestion
  --primary-color: #1065E0;
```

2020-09-23 13:39 UTC, dereksilva commented
Changes made, thanks @e-asia

2020-09-23 14:05 UTC, bonustrack commented
@e-asia We will wait final address later this week to merge this PR.

2020-09-24 12:41 UTC, e-asia commented
@dereksilva @bonustrack I just noticed that the images are a bit too heavy. They should weigh 50bk max. Thank you for that.

2020-09-24 13:08 UTC, dereksilva commented
Sorry, I did this yesterday but could only push the smaller images now.

2020-09-25 15:00 UTC, e-asia approved these changes

2020-09-25 15:09 UTC, merged