Add DANIMESQ space
bonustrack/snapshot-spaces pull request #92
Opened 2020-09-22 22:52 UTC by DaniellMesquita

Signed-off-by: Daniell Mesquita <daniellmesquita@protonmail.com>

2020-09-23 05:08 UTC, DaniellMesquita commented
@e-asia

2020-09-23 06:08 UTC, e-asia requested changes

2020-09-23 06:08 UTC, e-asia commented on spaces/daniell-mesquita/skin.scss
> +}
Scss indentation is not correct, you have to delete the extra quote. "}"
```suggestion
.daniell-mesquita {
  --primary-color: #f74174;
  --bg-color: #f74174;
  --text-color: #fff;
  --link-color: #fff;
  --heading-color: #fff;
  --border-color: #04b7bc;
  --header-bg: #04b7bc;
  --block-bg: transparent;
}
```

2020-09-23 06:29 UTC, DaniellMesquita commented
@e-asia ok!

2020-09-23 11:07 UTC, e-asia commented
@DaniellMesquita The images file size should not exceed 50KB. Please reduce their weight.

2020-09-23 15:59 UTC, DaniellMesquita commented
@e-asia still the same good icon and reduced much bellow 50KB!

2020-09-24 04:34 UTC, e-asia approved these changes

2020-09-24 12:47 UTC, merged